# Artificial Neural Network

Building an ANN Regression model to predict the electrical energy output of a Combined Cycle Power Plant

### Importing the libraries

In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [0]:
dataset = pd.read_excel('Regression_ANN.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [7]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

 sequential class will exactly create an artificial new network initialized as a sequence of layers.

In [0]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

units = the number of hidden neurons in this first hidden layer.

In [0]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

NO ACTIVATION FUNCTION needed for REGRESSION problems. (cause we need a cont. number as an answer)

In [0]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

Optimizer = 'adam' (Stochastic GD) <br/>
Loss for Regression is ALWAYS MSE  'mean_squared_error'

In [0]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [14]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 0s 1ms/step - loss: 220778.9062
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 721.8394
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 436.2952
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 425.0470
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 411.8244
Epoch 6/100
240/240 [==============================] - 0s 998us/step - loss: 396.5707
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 378.8057
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 360.0521
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 339.2090
Epoch 10/100
240/240 [==============================] - 0s 983us/step - loss: 316.9241
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 293.2366
Epoch 12/100
240/240 [==============================] - 0s 1ms/step

### Predicting the results of the Test set

In [15]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[431.71 431.23]
 [462.77 460.01]
 [466.24 461.14]
 ...
 [473.52 473.26]
 [440.27 438.  ]
 [459.51 463.28]]
